# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-08 11:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0002_auto_20170708_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
